### PR TITLE
Add support for confidential clients

### PR DESCRIPTION
**Pull request by erikwiffin**
This adds support for confidential apps as described in http://docs.smarthealthit.org/authorization/#app-exchanges-authorization-code-for-access-token.

I'm sorry about all the extra whitespace changes, my vim is set to automatically delete trailing whitespace on save. If this is an issue, I can figure out how to put them all back.

### CODE REVIEW

**Comment by jmandel** [comment]
Thanks @erikwiffin! If it's not too much trouble, it would be good if you could push a commit without the whitespace changes (e.g. "git add -p" and focus on the relevant hunks). 

@p2, would you give this a quick look?)

**Comment by p2** [comment]
Ha, I was completely oblivious of the fact that we didn't support confidential clients!

Thanks for this – fixing the whitespace changes would be great, otherwise looks good to me. 👍🏼

**Comment by p2** [comment]
Two additions:

1. Would be nice to have request decoration in `auth.py` instead, but that would require a more extensive update than this quick fix
2. Servers may ask for client id/secret in the request body. Once we want to support that we should revisit point 1.

**Comment by jmandel** [comment]
Can you explain what (1) would look like?

And re (2): for SMART on FHIR, we specify that the client id and secret are passed in an Authorization header when doing secret-based authentication. So (2) may not be immediately relevant.

**Comment by p2** [comment]
For 1), the idea is that the `Server` instance delegates all auth tasks to its `Auth` instance. It's not thoroughly implemented however, except in the server's [`_get()`](https://github.com/smart-on-fhir/client-py/blob/master/fhirclient/server.py#L176) method. In there the auth instance gets a chance to modify the request headers (and adds the access token if it has one) before the request is executed. Something similar for the token flow would be ideal, but would need more work for a clean solution.

So, for now at least, I'm fine with Erik's solution.

So 2) is not relevant on the SMART front – and it shouldn't be relevant on the OAuth2 front, hooray for flexible standards!

**Comment by erikwiffin** [comment]
I've force pushed a new commit without the whitespace changes. Should be good to go.

**Comment by p2** [comment]
Great, thanks for that!

**Comment by erikwiffin** [comment]
@p2 Is the extra whitespace a desired feature or just one of those things that accumulates over time? PEP 8 recommends removing it https://www.python.org/dev/peps/pep-0008/#other-recommendations, so if you don't care either way, I can send you another PR that gets rid of it everywhere so that I don't have to edit it out if I have any other feature requests.

**Comment by p2** [comment]
I for one always put that whitespace to keep the indentation level right, so I'm going against PEP-8 deliberately on this one. :)

**Comment by erikwiffin** [comment]
Fair enough, I'll leave it alone :)

**Pull request merged**
