### PR TITLE
Fix reauthorization to work beyond the first time called

### PR DESCRIPTION
**Pull request by timharsch**
Address issue in #112

### CODE REVIEW

**Review by ducu — APPROVED** [review]
Ok thank you

**Comment by ducu** [comment]
Please pull from upstream first, your branch is behind:

This branch is [1 commit ahead](https://github.com/Unite-Genomics/client-py/compare/smart-on-fhir:client-py:master...EN-2019), [71 commits behind](https://github.com/Unite-Genomics/client-py/compare/EN-2019...smart-on-fhir:client-py:master) smart-on-fhir:master.

**Comment by timharsch** [comment]
The branch being out of date goes back to the issue #112.  I still don't know what is expected here:

>In our case we only use the DSTU2 version of client-py and I don't see anything in the CONTRIBUTING.md document about how to target PRs, so I'll just leave my solution here (which is a commit added on top on the v1.0.6 tag)

My confusion, at the moment, is with how this project releases it's code.  I looked in the CONTRIBUTING.md document hoping to find an answer but it doesn't seem to be addressed.   As far as I can tell, there are tags for different level of FHIR support.   My code is based on the v1.0.6 tag, and since I am only concerned with DSTU2 support I can't run from master.  Should I target this PR against the v1.0.6 tag?  How would that even work?  I can only test with DSTU2 sandboxes at the moment, so if I target another tag or master, I will not be able to test.  If I bring my code current with master and target that with the PR, how would a version v.1.0.7 get released?

**Comment by ducu** [comment]
Ah yes right, not sure how releasing was done for this project I'll look into it. Anyway this PR into master is not working.

**Comment by timharsch** [comment]
I will reopen a new PR targeting master.  In the future, you may leave the PR open if you wish to maintain the story, as it is possible to change the source and target branches on an open PR.

**Pull request closed without merging**
