### PR TITLE
Fixed relative path to account for object creation with no id

### PR DESCRIPTION
**Pull request by ektar**

### CODE REVIEW

**Comment by p2** [comment]
Simple enough. I'm curious, in which use cases did you run into problems if id was None?

**Comment by p2** [comment]
(I will apply to upstream fhir-parser, since this is where it's coming from)

**Comment by ektar** [comment]
Below is the code I was trying, created a new patient and was trying to add to the server (hapi).  Saw the url it was trying to post to was "http://<server>/.../Patient/None", resulting in 400 errors.

    pat = patient.Patient()

    pat_id = identifier.Identifier()
    pat_id.value = "42"
    pat.identifier = [pat_id, ]

    pat_name = humanname.HumanName()
    pat_name.given = ["John", ]
    pat_name.family = ["Doe", ]
    pat.name = [pat_name, ]

    pat.create(smart.server)

**Comment by p2** [comment]
Huh, I see. Problem is that `create()` is calling `relativePath()` instead of `relativeBase()`, will fix as well.

**Pull request merged**
