### PR TITLE
Use requests.Session for HTTP requests

### PR DESCRIPTION
**Pull request by erikwiffin**

### CODE REVIEW

**Comment by erikwiffin** [comment]
This use of the requests Session solves my problem in https://github.com/smart-on-fhir/client-py/issues/18 (I have something to hook into for logging) and also moves handling of basic auth back into `auth.py`.

**Comment by p2** [comment]
The problem with this solution is that it always sends client id/secret to the FHIR endpoint. Maybe it makes sense to create a second `authSession` or similar?

**Comment by p2** [comment]
Haven't yet taken a thorough look, but I'm starting to think that moving the Server's `post_as_form()` method into Auth could work well. Then you can use `request.Session` as desired in this PR while leaving the client id and secret out of it, only using it inside Auth.

**Comment by erikwiffin** [comment]
I think you've got a good separation of concerns going on here, I don't think you want auth.py to be sending its own requests. What if post_as_form took a third, optional parameter?

```
def post_as_form(self, url, formdata, auth=None):
    ...
    res = requests.post(url, data=formdata, auth=auth)
```

**Comment by p2** [comment]
That sounds reasonable to me, yes.

**Comment by erikwiffin** [comment]
Force pushed an amended commit. I'm also passing `app_secret` into the auth state so that it doesn't need to check `self.server.client.app_secret`. I tried to follow the pattern everything else uses, but let me know if I missed anything.

**Comment by p2** [comment]
(Just a note, you don't need to force-push; pushing to the same branch will update the PR automatically.)

**Comment by p2** [comment]
Thanks, this looks awesome, all nice and clean!!

**Comment by erikwiffin** [comment]
Cool. Was just trying to adhere to the last bullet in contributing.md, but I guess now that github can automatically squash when merging that's less of an issue.

Thanks!

**Comment by p2** [comment]
Hey, I only [converted](https://github.com/smart-on-fhir/client-py/commit/43c72e97f616d58d1f949caa4be7c1cf03837ba5) contributing.md from rst to Markdown, doesn't mean I read it! ;)

**Pull request merged**
